name: AndroidLint

on:
  pull_request:
    branches:
      - main

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Create file
        run: cat /home/runner/work/Seminar/Seminar/app/google-services.json | base64
      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/Seminar/Seminar/app/google-services.json
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle
      - run: ./gradlew lint
      - uses: yutailang0119/action-android-lint@v4
        with:
          report-path: build/reports/*.xml
          ignore-warnings: true
        continue-on-error: false