name: Build & Upload AAB to Play Store

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build & Deploy AAB
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Write google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$DATA" | base64 --decode > app/google-services.json

      - name: Decode and Restore Keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo $KEYSTORE_BASE64 | base64 -d > release.keystore

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Calculate adjusted version number
        id: adjust_run_number
        run: echo "adjusted_run_number=$((GITHUB_RUN_NUMBER + 6))" >> $GITHUB_ENV
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}

      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ env.adjusted_run_number }}

      - name: Build Release AAB
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/release.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Upload AAB to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.suyogbauskar.calmora
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: beta
          whatsNewDirectory: whatsNew
