name: Lint and Build

on:
  pull_request:
    branches:
      - main

jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Write google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$DATA" | base64 --decode > app/google-services.json

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - run: ./gradlew lint

      - uses: yutailang0119/action-android-lint@v4
        with:
          report-path: build/reports/*.xml
          ignore-warnings: true
        continue-on-error: false

      - name: Build gradle project
        run: ./gradlew build
